/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// ===== PUSH NOTIFICATIONS =====
self.addEventListener('push', function (event) {
  console.log('[SW] 🔔 Push event received:', event);

  // Default fallback data
  let title = '📋 New Pick List';
  let body = 'بكلست جديدة';
  let url = '/';
  let icon = '/pwa-192x192.png';
  let badge = '/pwa-192x192.png';

  // Parse incoming data with multiple fallbacks
  if (event.data) {
    try {
      const parsed = event.data.json();
      console.log('[SW] 📦 Parsed push data:', parsed);
      
      title = parsed.title || title;
      body = parsed.body || parsed.message || body;
      url = parsed.url || parsed.link || url;
      icon = parsed.icon || icon;
      badge = parsed.badge || badge;
    } catch (e) {
      console.log('[SW] ⚠️ Failed to parse JSON, trying text:', e);
      try {
        body = event.data.text() || body;
      } catch (e2) {
        console.log('[SW] ⚠️ Failed to parse text, using defaults:', e2);
      }
    }
  } else {
    console.log('[SW] ℹ️ No push data, using defaults');
  }

  const options: NotificationOptions = {
    body: body,
    icon: icon,
    badge: badge,
    vibrate: [200, 100, 200, 100, 200],
    tag: 'picklist-notification',
    renotify: true,
    requireInteraction: false,
    silent: false,
    data: { 
      url: url, 
      timestamp: Date.now(),
      clickAction: url 
    },
  };

  console.log('[SW] 🔔 Showing notification:', title, options);

  // Critical: waitUntil ensures SW stays alive until notification is shown
  event.waitUntil(
    self.registration.showNotification(title, options)
      .then(() => {
        console.log('[SW] ✅ Notification displayed successfully');
      })
      .catch((error) => {
        console.error('[SW] ❌ Failed to show notification:', error);
      })
  );
});

self.addEventListener('notificationclick', function (event) {
  console.log('[SW] Notification clicked');
  event.notification.close();

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (clientList) {
        for (const client of clientList) {
          if ('focus' in client) {
            return client.focus();
          }
        }
        return self.clients.openWindow('/');
      })
  );
});

// Keep SW alive - respond to periodic sync if available
self.addEventListener('periodicsync', function (event: any) {
  if (event.tag === 'keep-alive') {
    event.waitUntil(Promise.resolve());
  }
});
