/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// ===== PUSH NOTIFICATIONS =====
self.addEventListener('push', function (event) {
  console.log('[SW] Push received:', event);

  let data = { title: '📋 New Pick List', body: 'بكلست جديدة' };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options: any = {
    body: data.body || 'بكلست جديدة',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200],
    tag: 'picklist-' + Date.now(),
    renotify: true,
    requireInteraction: true,
    data: { url: '/' },
  };

  event.waitUntil(
    self.registration.showNotification(data.title || '📋 New Pick List', options)
  );
});

self.addEventListener('notificationclick', function (event) {
  console.log('[SW] Notification clicked');
  event.notification.close();

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function (clientList) {
        for (const client of clientList) {
          if (client.visibilityState === 'visible') {
            return client.focus();
          }
        }
        return self.clients.openWindow('/');
      })
  );
});
